version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
        - cd ./my-react-app
        - npm install
       
  build:
    commands:
        - npm run build
     
artifacts:
  files:
    - '**/*'
    - '../appspec.yml'
    - '../scripts/**/*'
  base-directory: './my-react-app/dist'
  discard-paths: no